Repository icssc/AntAlmanac, pull requests merged in 2023-03, with the labels that each got.

#518 news scroll looks good
  apps/client/src/components/Header/News.tsx
Labels: enhancement

#498 Custom Buttons
  src/components/Buttons/AddCourse.tsx
  src/components/Buttons/AddCourseMenu.tsx
  src/components/Buttons/ClearSchedule.tsx
  src/components/Buttons/ColorPicker.tsx
  src/components/Buttons/CourseReference.tsx
  src/components/Buttons/CourseSummary.tsx
  src/components/Buttons/CustomEvent.tsx
  src/components/Buttons/DeleteCourse.tsx
  src/components/Buttons/DeleteSchedule.tsx
  src/components/Buttons/Download.tsx
  src/components/Buttons/Redo.tsx
  src/components/Buttons/RenameSchedule.tsx
  src/components/Buttons/Screenshot.tsx
  src/components/Buttons/SelectSchedule.tsx
  src/components/Buttons/ToggleFinals.tsx
  src/components/Buttons/Undo.tsx
  src/lib/download.ts
  src/stores/schedule/course.ts
Labels: codefix

#488 Map link
  .gitignore
  src/components/AppBar/AboutPage.tsx
  src/components/AppBar/CustomAppBar.tsx
  src/components/Calendar/CourseCalendarEvent.tsx
  src/components/Calendar/Toolbar/CustomEventDialog/DaySelector.tsx
  src/components/Calendar/Toolbar/CustomEventDialog/ScheduleSelector.tsx
  src/components/Calendar/Toolbar/ExportCalendar.tsx
  src/components/Calendar/Toolbar/ScreenshotButton.tsx
  src/components/MobileHome.tsx
  src/components/PatchNotes.tsx
  src/components/RightPane/CoursePane/CoursePaneRoot.tsx
  src/components/RightPane/CoursePane/CourseRenderPane.tsx
  src/components/RightPane/CoursePane/SearchForm/DeptSearchBar/MobileDeptSelector.tsx
  src/components/RightPane/CoursePane/SearchForm/FuzzySearch.tsx
  src/components/RightPane/CoursePane/SearchForm/GESelector.tsx
  src/components/RightPane/CoursePane/SearchForm/SectionCodeSearchBar.tsx
  src/components/RightPane/CoursePane/SearchForm/TermSelector.tsx
  src/components/RightPane/Map/MapMarker.tsx
  src/components/RightPane/Map/UCIMap.tsx
  src/components/RightPane/RightPaneRoot.tsx
  src/components/RightPane/RightPaneStore.ts
  src/components/RightPane/SectionTable/GEDataFetchProvider.tsx
  src/components/RightPane/SectionTable/SectionTable.tsx
  src/components/RightPane/SectionTable/SectionTableBody.tsx
  src/index.tsx
  src/lib/helpers.ts
  src/registerServiceWorker.js
  vite.config.ts
  yarn.lock
Labels: enhancement

#530 Fix map-linking bugs
  src/components/RightPane/Map/MapMarker.tsx
  src/components/RightPane/Map/UCIMap.tsx
Labels: bug
