Repository icssc/AntAlmanac, pull requests merged in 2023-05, with the labels that each got.

#568 Update Map & Routes When Changing Schedules
  apps/antalmanac/src/components/RightPane/Map/UCIMap.tsx
Labels: enhancement

#559 Add section type to calendar event popup
  apps/antalmanac/src/components/Calendar/CourseCalendarEvent.tsx
Labels: enhancement

#548 Different sections have different default colors.
  apps/antalmanac/src/stores/Schedules.ts
  apps/antalmanac/src/stores/schedule.types.ts
Labels: enhancement

#576 Fix for Unremoved Markers - Unique Keys for Children
  apps/antalmanac/src/components/RightPane/Map/UCIMap.tsx
Labels: bug

#594 Fix RMP url scheme
  apps/antalmanac/src/components/RightPane/SectionTable/SectionTableBody.tsx
Labels: high
