Repository icssc/AntAlmanac, pull requests merged in 2024-02, with the labels that each got.

#887 style: add back row styling
  apps/antalmanac/src/components/RightPane/SectionTable/SectionTableBody.tsx
Labels: high

#894 chore: add console.error in error spots to help developer
  apps/antalmanac/src/actions/AppStoreActions.ts
  apps/antalmanac/src/stores/Schedules.ts
Labels: no deploy

#896 fix: respect the no deploy label
  .github/workflows/deploy_staging.yml
Labels: no deploy

#897 chore: add spring 2024 to termData
  apps/antalmanac/src/lib/termData.ts
  apps/antalmanac/tests/__snapshots__/download-ics.test.ts.snap
  apps/antalmanac/tests/calendarize-helpers.test.ts
Labels: high

#910 fix: refactor screenshot to function component, fixing use w/ ThemeStore
  apps/antalmanac/src/components/buttons/Screenshot.tsx
Labels: bug, high
