Repository icssc/AntAlmanac, pull requests merged in 2024-10, with the labels that each got.

#1004 feat(download.ts): add location attribute to custom events
  apps/antalmanac/src/lib/download.ts
Labels: enhancement

#1008 Update required pnpm version
  .github/actions/setup-node-and-pnpm/action.yml
  .github/workflows/test.yaml
  apps/cdk/package.json
  package.json
  pnpm-lock.yaml
Labels: dependencies, high

#1014 Correctly link internal packages in package.json files
  apps/backend/package.json
  packages/types/package.json
  pnpm-lock.yaml
Labels: dependencies
