Repository icssc/AntAlmanac, pull requests merged in 2025-05, with the labels that each got.

#1216 fix: 🐛 finals throws error
  apps/antalmanac/src/stores/calendarizeHelpers.ts
  apps/antalmanac/tests/calendarize-helpers.test.ts
Labels: Stale

#1219 feat: changed Reviews button to PeterPortal button
  apps/antalmanac/src/assets/peterportal-logo.png
  apps/antalmanac/src/components/RightPane/SectionTable/SectionTable.tsx
Labels: Stale

#1255 Redeploy every 15 minutes
  .github/workflows/deploy_production.yml
Labels: bug

#1261 Add ANTEATER_API_KEY to backend vars parsing
  apps/backend/src/env.ts
  apps/backend/src/index.ts
Labels: bug, backend

#1270 AANTS Workflows
  .github/workflows/deploy_production.yml
  .github/workflows/deploy_staging.yml
Labels: backend
