Repository icssc/AntAlmanac, pull requests merged in 2025-01, with the labels that each got.

#1099 fix: hide scrollbars on mobile devices
  apps/antalmanac/src/App.css
Labels: enhancement

#1086 feat: cache websoc
  .eslintrc.cjs
  apps/antalmanac/src/actions/AppStoreActions.ts
  apps/antalmanac/src/components/RightPane/SectionTable/CourseInfo/CourseInfoBar.tsx
  apps/antalmanac/src/components/RightPane/SectionTable/CourseInfo/CourseInfoButton.tsx
  apps/antalmanac/src/components/RightPane/SectionTable/CourseInfo/CourseInfoSearchButton.tsx
  apps/antalmanac/src/components/RightPane/SectionTable/PrereqTree.tsx
  apps/antalmanac/src/components/RightPane/SectionTable/SectionTable.tsx
  apps/antalmanac/src/components/RightPane/SectionTable/cells/action.tsx
  apps/antalmanac/src/lib/websoc.ts
  apps/antalmanac/src/stores/Schedules.ts
  apps/backend/src/routers/websoc.ts
  eslint.config.mjs
  package.json
  pnpm-lock.yaml
Labels: codefix

#1115 Increase backend lambda timeout to 20 seconds
  apps/cdk/src/stacks/backend.ts
Labels: bug, backend

#1109 Post-migration cleanup
  apps/backend/.env.example
  apps/backend/package.json
  apps/backend/scripts/ddb_to_rds.ts
  apps/backend/src/db/ddb.ts
  apps/backend/src/env.ts
  apps/backend/src/routers/users.ts
  pnpm-lock.yaml
Labels: backend

#1105 refactor: schedule management and tab store
  apps/antalmanac/src/components/Calendar/CourseCalendarEvent.tsx
  apps/antalmanac/src/components/Map/Map.tsx
  apps/antalmanac/src/components/RightPane/AddedCourses/AddedCoursePane.tsx
  apps/antalmanac/src/components/RightPane/SectionTable/SectionTableBody/SectionTableBodyCells/ActionCell.tsx
  apps/antalmanac/src/components/RightPane/SectionTable/SectionTableBody/SectionTableBodyRow.tsx
  apps/antalmanac/src/components/ScheduleManagement/ScheduleManagement.tsx
  apps/antalmanac/src/components/ScheduleManagement/ScheduleManagementContent.tsx
  apps/antalmanac/src/components/ScheduleManagement/ScheduleManagementTab.tsx
  apps/antalmanac/src/components/ScheduleManagement/ScheduleManagementTabs.tsx
  apps/antalmanac/src/components/SharedRoot.tsx
  apps/antalmanac/src/components/buttons/MapLink.tsx
  apps/antalmanac/src/lib/TutorialHelpers.tsx
  apps/antalmanac/src/lib/helpers.ts
  apps/antalmanac/src/routes/Home.tsx
  apps/antalmanac/src/stores/AppStore.ts
  apps/antalmanac/src/stores/TabStore.ts
Labels: codefix

#1130 refactor: peterportal alert
  apps/antalmanac/src/components/RightPane/CoursePane/CourseRenderPane.tsx
Labels: enhancement
